name: news_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.3.1
  webview_flutter: ^2.0.8
  connectivity_plus: ^1.0.3
  shimmer: ^2.0.0
  hive: ^2.0.4
  provider: ^5.0.0
  path_provider: ^2.1.3
  transition: ^2.0.2
  url_launcher: ^6.0.12
  share_plus: ^10.0.2
  cupertino_icons: ^1.0.2
  firebase_core: ^3.2.0
  cloud_firestore: ^5.1.0
  flutter_dotenv: ^5.1.0
  intl:
  flutter_spinkit: ^5.2.1
  lottie: ^3.1.2
  video_player: ^2.9.2
  font_awesome_flutter: ^10.7.0
  image_picker: ^0.8.4+9
  flutter_reaction_button: ^3.0.0+2
  firebase_storage: ^12.3.0
  shared_preferences: ^2.0.0
  firebase_auth: ^5.2.1
  firebase_messaging: ^15.1.3
  rolling_bottom_bar: ^0.2.2
  http: ^1.2.2
  swipe_refresh: ^1.1.2
  multi_dropdown: ^3.0.1
  datetime_picker_formfield_new: ^2.1.0



dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"


flutter:
  uses-material-design: true
  assets:
    - assets/
    - .env
    - assets/logo.mp4
    - assets/background/
    - assets/reactions/
    - assets/story/
